"""Add processing metadata fields

Revision ID: 1589802be311
Revises: cee22c6ead1d
Create Date: 2026-08-21 18:37:08.597712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1589802be311'
down_revision: Union[str, Sequence[str], None] = 'cee22c6ead1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_material', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('study_material', sa.Column('processing_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_material', 'processing_error')
    op.drop_column('study_material', 'processed_at')
    # ### end Alembic commands ###
