"""Add exam engine fields

Revision ID: 352fcea8d3b0
Revises: 4489d3f25cee
Create Date: 2026-08-21 20:28:21.047450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '352fcea8d3b0'
down_revision: Union[str, Sequence[str], None] = '4489d3f25cee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('selected_option_id', sa.String(length=255), nullable=True))
    op.add_column('answer', sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('answer', 'answer_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('mock_test', sa.Column('duration_minutes', sa.Integer(), nullable=False))
    op.add_column('mock_test', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('mock_test', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('mock_test', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mock_test', 'submitted_at')
    op.drop_column('mock_test', 'expires_at')
    op.drop_column('mock_test', 'started_at')
    op.drop_column('mock_test', 'duration_minutes')
    op.alter_column('answer', 'answer_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('answer', 'answered_at')
    op.drop_column('answer', 'selected_option_id')
    # ### end Alembic commands ###
