"""Add question bank support

Revision ID: 4489d3f25cee
Revises: 1589802be311
Create Date: 2026-08-21 20:21:48.610139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4489d3f25cee'
down_revision: Union[str, Sequence[str], None] = '1589802be311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_test_question',
    sa.Column('test_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['mock_test.id'], ),
    sa.PrimaryKeyConstraint('test_id', 'question_id')
    )
    op.add_column('question', sa.Column('subject_id', sa.Uuid(), nullable=False))
    op.add_column('question', sa.Column('topic_id', sa.Uuid(), nullable=True))
    op.add_column('question', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('question', sa.Column('source', sa.String(length=50), nullable=False))
    op.add_column('question', sa.Column('source_reference', sa.String(length=255), nullable=True))
    op.add_column('question', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('question', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('question_test_id_fkey'), 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'subject', ['subject_id'], ['id'])
    op.create_foreign_key(None, 'question', 'user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'question', 'topic', ['topic_id'], ['id'])
    op.drop_column('question', 'test_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('test_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key(op.f('question_test_id_fkey'), 'question', 'mock_test', ['test_id'], ['id'])
    op.drop_column('question', 'created_by')
    op.drop_column('question', 'status')
    op.drop_column('question', 'source_reference')
    op.drop_column('question', 'source')
    op.drop_column('question', 'explanation')
    op.drop_column('question', 'topic_id')
    op.drop_column('question', 'subject_id')
    op.drop_table('mock_test_question')
    # ### end Alembic commands ###
