"""Update StudyMaterial model

Revision ID: cee22c6ead1d
Revises: cc20e921ff84
Create Date: 2026-08-21 18:15:56.530638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cee22c6ead1d'
down_revision: Union[str, Sequence[str], None] = 'cc20e921ff84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_material', sa.Column('file_name', sa.String(length=255), nullable=False))
    op.add_column('study_material', sa.Column('file_type', sa.String(length=50), nullable=False))
    op.add_column('study_material', sa.Column('mime_type', sa.String(length=100), nullable=False))
    op.add_column('study_material', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('study_material', sa.Column('storage_key', sa.String(length=500), nullable=False))
    op.add_column('study_material', sa.Column('processing_status', sa.String(length=50), nullable=False))
    op.drop_column('study_material', 'file_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_material', sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('study_material', 'processing_status')
    op.drop_column('study_material', 'storage_key')
    op.drop_column('study_material', 'file_size')
    op.drop_column('study_material', 'mime_type')
    op.drop_column('study_material', 'file_type')
    op.drop_column('study_material', 'file_name')
    # ### end Alembic commands ###
